// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO9ZRrgmazf0ZQ7rO0DsOZIZBtcJh5Qa4',
    appId: '1:1018588279964:web:cca35d0638fff65a052959',
    messagingSenderId: '1018588279964',
    projectId: 'calendar-e5714',
    authDomain: 'calendar-e5714.firebaseapp.com',
    storageBucket: 'calendar-e5714.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdtTxLfn2lV5X_QC8-VYTtysvboiCDJg',
    appId: '1:1018588279964:android:ee2ef4af8270aaf6052959',
    messagingSenderId: '1018588279964',
    projectId: 'calendar-e5714',
    storageBucket: 'calendar-e5714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChblQZGpLA6-hkh1_WKIGu0wmXWZQ02TM',
    appId: '1:1018588279964:ios:78c1973c06f1ac89052959',
    messagingSenderId: '1018588279964',
    projectId: 'calendar-e5714',
    storageBucket: 'calendar-e5714.appspot.com',
    iosClientId:
        '1018588279964-c25op6s8bc3kkfb8sf8tlig49obgts3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChblQZGpLA6-hkh1_WKIGu0wmXWZQ02TM',
    appId: '1:1018588279964:ios:78c1973c06f1ac89052959',
    messagingSenderId: '1018588279964',
    projectId: 'calendar-e5714',
    storageBucket: 'calendar-e5714.appspot.com',
    iosClientId:
        '1018588279964-c25op6s8bc3kkfb8sf8tlig49obgts3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO9ZRrgmazf0ZQ7rO0DsOZIZBtcJh5Qa4',
    appId: '1:1018588279964:web:e0c196cadf077536052959',
    messagingSenderId: '1018588279964',
    projectId: 'calendar-e5714',
    authDomain: 'calendar-e5714.firebaseapp.com',
    storageBucket: 'calendar-e5714.appspot.com',
  );
}
